[build-system]
requires = ["setuptools", "versioningit~=0.3.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.versioningit]

[tool.versioningit.vcs]
method = "git"
match = ["v*"]
default-tag = "0.0.0"

[tool.versioningit.tag2version]
rmprefix = "v"
