name: Publish Version

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Guess Testing
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Publish Python Package
        run: |
          python -m pip install build twine
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
