name: Stage Tests

on: [ push ]

jobs:
  local-tests:
    name: Test Code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Guess Testing
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install --upgrade pip

          pip install -r requirements-dev.txt

      - name: Inspect Code Quality
        run: |
          echo Imports sorting:
            isort \
              --multi-line HANGING_INDENT \
              --line-length=120 \
              --diff \
              guess_testing \
            | tee isort.txt

          if [ -s isort.txt ]; then
            exit 1
          fi

          echo Linter warnings:
          pylint \
            --disable=C0114,C0415,R0903,R0913,R0914,W0212,W0511 \
            --max-line-length=120 \
            guess_testing

      - name: Inspect Vulnerabilities
        run: |
          echo Vulnerabilities:
          bandit \
            --skip B307,B311 \
            --recursive guess_testing
